- name: myFirstRepo
  type: GitRepo
  configuration:
    # SCM integration where the repository is located
    gitProvider: {{ Values.myRepo.gitProvider }}
    # Repository path, including org name/repo name
    path: {{ Values.myRepo.path }} #manishas-jfrog/jfrog-pipelines-hello-world    # replace with your repository name
    branches:
      # Specifies which branches will trigger dependent steps
      include: main
      
pipelines:
  - name: hello
    steps:
      - name: hello
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
        execution:
          onExecute:
            - echo "Hello World!"
