- name: myFirstRepo
  type: GitRepo
  configuration:
    gitProvider: test
    path: snarky/tests 
    branches:
      include: main
      
pipelines:
  - name: hello
    steps:
      - name: hello
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: myFirstRepo
        execution:
          onExecute:
            - echo "Hello World!"
